export default [
    {
        id: 1,
        first_name: 'Jane',
        last_name: 'Cooper',
        direction: 'Cooper',
        phone_number: '(225) 555-0118',
        pay: '697 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 2,
        first_name: 'Floyd',
        last_name: 'Miles',
        direction: 'Yahoo',
        phone_number: '(205) 555-0100',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 3,
        first_name: 'Ronald',
        last_name: 'Richards',
        direction: 'Adobe',
        phone_number: '(302) 555-0107',
        pay: 'ronald@adobe.com',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 4,
        first_name: 'Marvin',
        last_name: 'McKinney',
        direction: 'Tesla',
        phone_number: '(252) 555-0126',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 5,
        first_name: 'Jerome',
        last_name: 'Bell',
        direction: 'Google',
        phone_number: '(629) 555-0129',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 6,
        first_name: 'Kathryn',
        last_name: 'Murphy',
        direction: 'Microsoft',
        phone_number: '(406) 555-0120',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 7,
        first_name: 'Jacob',
        last_name: 'Jones',
        direction: 'Yahoo',
        phone_number: '(208) 555-0112',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 8,
        first_name: 'Kristin',
        last_name: 'Watson',
        direction: 'Facebook',
        phone_number: '(704) 555-0127',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 9,
        first_name: 'Ronald',
        last_name: 'Richards',
        direction: 'Tesla',
        phone_number: '(406) 555-0120',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 10,
        first_name: 'Ronald',
        last_name: 'Richards',
        direction: 'Microsoft',
        phone_number: '(225) 555-0118',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 11,
        first_name: 'Jerome',
        last_name: 'Bell',
        direction: 'Yahoo',
        phone_number: '(629) 555-0129',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 12,
        first_name: 'Floyd',
        last_name: 'Miles',
        direction: 'Tesla',
        phone_number: '(406) 555-0120',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 13,
        first_name: 'Jane',
        last_name: 'Cooper',
        direction: 'Tesla',
        phone_number: '(302) 555-0107',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 14,
        first_name: 'Kathryn',
        last_name: 'Murphy',
        direction: 'Microsoft',
        phone_number: '(704) 555-0127',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 15,
        first_name: 'Jacob',
        last_name: 'Jones',
        direction: 'Yahoo',
        phone_number: '(208) 555-0112',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 16,
        first_name: 'Marvin',
        last_name: 'McKinney',
        direction: 'Google',
        phone_number: '(252) 555-0126',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 17,
        first_name: 'Jane',
        last_name: 'Cooper',
        direction: 'Yahoo',
        phone_number: '(205) 555-0100',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 18,
        first_name: 'Ronald',
        last_name: 'Richards',
        direction: 'Adobe',
        phone_number: '(205) 555-0100',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 19,
        first_name: 'Jerome',
        last_name: 'Bell',
        direction: 'Microsoft',
        phone_number: '(629) 555-0129',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 20,
        first_name: 'Ronald',
        last_name: 'Richards',
        direction: 'Google',
        phone_number: '(704) 555-0127',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 21,
        first_name: 'Ronald',
        last_name: 'Richards',
        direction: 'Yahoo',
        phone_number: '(302) 555-0107',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 22,
        first_name: 'Marvin',
        last_name: 'McKinney',
        direction: 'Google',
        phone_number: '(629) 555-0129',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'active',
    },
    {
        id: 23,
        first_name: 'Floyd',
        last_name: 'Miles',
        direction: 'Google',
        phone_number: '(205) 555-0100',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
    {
        id: 24,
        first_name: 'Kathryn',
        last_name: 'Murphy',
        direction: 'Yahoo',
        phone_number: '(629) 555-0129',
        pay: '597 000',
        group: 'Frontend 010',
        status: 'inactive',
    },
]
